import { NextResponse, type NextRequest } from 'next/server'
import type { EmailOtpType } from '@supabase/supabase-js'
import { defaultLocale, isLocale } from '@/i18n/routing'
import { classifyExchangeFailure } from '@/lib/auth/errors'
import { safeRedirectPath } from '@/lib/auth/routes'
import { createClient } from '@/lib/supabase/server'

const OTP_TYPES: ReadonlySet<string> = new Set(['magiclink', 'email', 'signup', 'recovery', 'invite', 'email_change'])

/**
 * Where a link carrying a session lands.
 *
 * Nobody arrives here in normal use — the app opens straight into the plan and
 * asks for nothing — but this is how a session can still be handed to a
 * browser deliberately: the end-to-end suite signs its fixture athletes in
 * this way, which is what keeps the tests that prove one athlete cannot read
 * another's rows honest.
 *
 * Two forms, both of which end with the session written to cookies:
 *   - `code`: the PKCE exchange, which is what a link generated for a browser
 *     that asked for one comes back with.
 *   - `token_hash` + `type`: direct verification of an email OTP, the pattern
 *     Supabase documents for server-rendered apps. It needs no redirect through
 *     the auth server, so it also works for links generated by the admin API.
 *
 * Either way the visitor is then sent where they were headed — validated
 * first, so a crafted `next` cannot bounce them off-site with a fresh session.
 * A failure has nowhere to send anyone but the page that explains the app.
 */
export async function GET(request: NextRequest) {
  const { searchParams, origin } = new URL(request.url)
  const localeParam = searchParams.get('locale')
  const locale = localeParam && isLocale(localeParam) ? localeParam : defaultLocale
  const next = safeRedirectPath(searchParams.get('next'), locale)

  const code = searchParams.get('code')
  const tokenHash = searchParams.get('token_hash')
  const type = searchParams.get('type')

  const supabase = await createClient()

  if (code) {
    const { error } = await supabase.auth.exchangeCodeForSession(code)
    if (error) return NextResponse.redirect(`${origin}/${locale}/welcome?error=${classifyExchangeFailure(error)}`)
    return NextResponse.redirect(`${origin}${next}`)
  }

  if (tokenHash && type && OTP_TYPES.has(type)) {
    const { error } = await supabase.auth.verifyOtp({ token_hash: tokenHash, type: type as EmailOtpType })
    if (error) return NextResponse.redirect(`${origin}/${locale}/welcome?error=exchange_failed`)
    return NextResponse.redirect(`${origin}${next}`)
  }

  return NextResponse.redirect(`${origin}/${locale}/welcome?error=missing_code`)
}
