// Generated by scripts/gen-db-types.py from the Postgres schema. Do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      body_measurements: {
        Row: {
          id: string
          user_id: string
          date: string
          weight_kg: number | null
          waist_cm: number | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date: string
          weight_kg?: number | null
          waist_cm?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          weight_kg?: number | null
          waist_cm?: number | null
          created_at?: string
        }
        Relationships: []
      }
      exercise_preferences: {
        Row: {
          id: string
          user_id: string
          slot_key: string | null
          from_exercise_id: string
          to_exercise_id: string | null
          scope: string
          date: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          slot_key?: string | null
          from_exercise_id: string
          to_exercise_id?: string | null
          scope: string
          date?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          slot_key?: string | null
          from_exercise_id?: string
          to_exercise_id?: string | null
          scope?: string
          date?: string | null
          created_at?: string
        }
        Relationships: []
      }
      food_logs: {
        Row: {
          id: string
          user_id: string
          date: string
          name: string
          kcal: number
          protein_g: number
          carbs_g: number
          fat_g: number
          logged_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date: string
          name: string
          kcal: number
          protein_g?: number
          carbs_g?: number
          fat_g?: number
          logged_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          name?: string
          kcal?: number
          protein_g?: number
          carbs_g?: number
          fat_g?: number
          logged_at?: string
          created_at?: string
        }
        Relationships: []
      }
      group_invites: {
        Row: {
          id: string
          group_id: string
          code: string
          created_by: string
          expires_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          group_id: string
          code: string
          created_by: string
          expires_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          group_id?: string
          code?: string
          created_by?: string
          expires_at?: string | null
          created_at?: string
        }
        Relationships: []
      }
      group_members: {
        Row: {
          group_id: string
          user_id: string
          role: string
          share_details: boolean
          joined_at: string
        }
        Insert: {
          group_id: string
          user_id: string
          role?: string
          share_details?: boolean
          joined_at?: string
        }
        Update: {
          group_id?: string
          user_id?: string
          role?: string
          share_details?: boolean
          joined_at?: string
        }
        Relationships: []
      }
      groups: {
        Row: {
          id: string
          name: string
          owner_id: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          owner_id: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          owner_id?: string
          created_at?: string
        }
        Relationships: []
      }
      planned_sessions: {
        Row: {
          id: string
          user_id: string
          plan_id: string
          date: string
          type: string
          content: Json
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          plan_id: string
          date: string
          type: string
          content: Json
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          plan_id?: string
          date?: string
          type?: string
          content?: Json
          created_at?: string
        }
        Relationships: []
      }
      plans: {
        Row: {
          id: string
          user_id: string
          block: number
          start_date: string
          weeks: number
          settings: Json
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          block: number
          start_date: string
          weeks: number
          settings: Json
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          block?: number
          start_date?: string
          weeks?: number
          settings?: Json
          created_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          user_id: string
          display_name: string
          locale: string
          timezone: string
          units: string
          sex: string | null
          birth_date: string | null
          height_cm: number | null
          health_flags: Json
          conservative_mode: boolean
          onboarded_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          user_id: string
          display_name: string
          locale?: string
          timezone?: string
          units?: string
          sex?: string | null
          birth_date?: string | null
          height_cm?: number | null
          health_flags?: Json
          conservative_mode?: boolean
          onboarded_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          user_id?: string
          display_name?: string
          locale?: string
          timezone?: string
          units?: string
          sex?: string | null
          birth_date?: string | null
          height_cm?: number | null
          health_flags?: Json
          conservative_mode?: boolean
          onboarded_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      questionnaire_answers: {
        Row: {
          id: string
          user_id: string
          version: number
          answers: Json
          active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          version: number
          answers: Json
          active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          version?: number
          answers?: Json
          active?: boolean
          created_at?: string
        }
        Relationships: []
      }
      run_logs: {
        Row: {
          id: string
          user_id: string
          session_log_id: string | null
          date: string
          planned_type: string | null
          minutes: number | null
          km: number | null
          avg_pace_s_per_km: number | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          session_log_id?: string | null
          date: string
          planned_type?: string | null
          minutes?: number | null
          km?: number | null
          avg_pace_s_per_km?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          session_log_id?: string | null
          date?: string
          planned_type?: string | null
          minutes?: number | null
          km?: number | null
          avg_pace_s_per_km?: number | null
          created_at?: string
        }
        Relationships: []
      }
      session_logs: {
        Row: {
          id: string
          user_id: string
          planned_session_id: string | null
          date: string
          readiness: Json | null
          done: boolean
          notes: string | null
          started_at: string | null
          completed_at: string | null
          created_at: string
          updated_at: string
          pain: Json | null
        }
        Insert: {
          id?: string
          user_id: string
          planned_session_id?: string | null
          date: string
          readiness?: Json | null
          done?: boolean
          notes?: string | null
          started_at?: string | null
          completed_at?: string | null
          created_at?: string
          updated_at?: string
          pain?: Json | null
        }
        Update: {
          id?: string
          user_id?: string
          planned_session_id?: string | null
          date?: string
          readiness?: Json | null
          done?: boolean
          notes?: string | null
          started_at?: string | null
          completed_at?: string | null
          created_at?: string
          updated_at?: string
          pain?: Json | null
        }
        Relationships: []
      }
      set_logs: {
        Row: {
          id: string
          user_id: string
          session_log_id: string
          exercise_id: string
          set_index: number
          kg: number | null
          reps: number | null
          rpe: number | null
          done: boolean
          logged_at: string
        }
        Insert: {
          id?: string
          user_id: string
          session_log_id: string
          exercise_id: string
          set_index: number
          kg?: number | null
          reps?: number | null
          rpe?: number | null
          done?: boolean
          logged_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          session_log_id?: string
          exercise_id?: string
          set_index?: number
          kg?: number | null
          reps?: number | null
          rpe?: number | null
          done?: boolean
          logged_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      group_weekly_summary: {
        Args: { p_group_id: string }
        Returns: { member_id: string; display_name: string; sessions_done_this_week: number; streak_days: number }[]
      }
      join_group_with_code: { Args: { p_code: string }; Returns: string }
      create_group: { Args: { p_name: string }; Returns: string }
      export_my_data: { Args: Record<string, never>; Returns: Json }
      delete_my_account: { Args: Record<string, never>; Returns: undefined }
      training_streak: { Args: { p_user_id: string }; Returns: number }
      is_group_member: { Args: { p_group_id: string; p_user_id: string }; Returns: boolean }
      is_group_owner: { Args: { p_group_id: string; p_user_id: string }; Returns: boolean }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

type PublicSchema = Database['public']
export type Tables<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Row']
export type TablesInsert<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Update']
